version: '3.4'

services:
  server:
    build: server/
    tty: true
    stdin_open: true
    volumes: 
      - "./server:/usr/server"
    ports:
      - "5555:5555"
    working_dir: "/usr/server"
    #command: "/bin/sh start_commands.sh"
    networks:
      app_net:
        ipv4_address: 172.19.0.2
    
  client:
    depends_on: [server]
    build: client/
    tty: true
    stdin_open: true
    volumes: 
      - "./client:/usr/client"
    ports:
      - "3000"
    working_dir: "/usr/client"
    #command: "./client"
    networks:
      app_net:
        ipv4_address: 172.19.0.3
    
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br_net



