version: '3.4'

services:
  router:
    image: 'dockersecplayground/alpine_router:v1.0'
    stdin_open: true
    tty: true
    networks:
      external_network:
        ipv4_address: 192.168.3.2
      internal_network:
        ipv4_address: 192.168.2.2
    cap_add:
      - ALL
    privileged: true

  server:
    build: server/
    tty: true
    stdin_open: true
    volumes: 
      - "./server:/usr/server"
    ports:
      - "443"
    working_dir: "/usr/server"
    command: /bin/sh start_commands.sh
    networks:
      internal_network:
        ipv4_address: 192.168.2.3
    cap_add:
      - ALL
    
  client:
    depends_on: [server]
    build: client/
    tty: true
    stdin_open: true
    volumes: 
      - "./client:/usr/client"
    working_dir: "/usr/client"
    command: /bin/sh start_commands.sh
    networks:
      external_network:
        ipv4_address: 192.168.3.4
    cap_add:
      - ALL
  
  sniffer:
    image: nsunina/wireshark:v1.1
    depends_on: [server]
    tty: true
    stdin_open: true
    ports:
      - "14500:14500"
    environment:
      - XPRA_PW=wireshark
    cap_add:
      - ALL
    privileged: true
    user: root
    command: >
      /bin/bash -c "apt-get install -y net-tools &&
      apt-get install -y dsniff &&
      route add default gw router &&
      echo 1 > /proc/sys/net/ipv4/ip_forward &&
      /usr/bin/xpra start --daemon=no --no-printing"
    networks:
      external_network:
        ipv4_address: 192.168.3.5

networks:
  external_network:
    ipam:
      config:
        - subnet: 192.168.3.1/24
  internal_network:
    ipam:
      config:
        - subnet: 192.168.2.1/24
