version: '2'
services:
  ComputerAFL:
    image: 'dockersecplayground/afl:latest'
    stdin_open: true
    tty: true
  ServerHttps:
    image: 'alessandro123456/heartbleed:latest'
    stdin_open: true
    tty: true
    networks:
      network_2:
        ipv4_address: 193.20.3.3
  Metasploit:
    image: 'dockersecplayground/kali:v1.0'
    stdin_open: true
    tty: true
    networks:
      network_2: {}
    cap_add:
      - ALL
    privileged: true
  ClientWfuzz:
    image: 'dockersecplayground/client_wfuzz:latest'
    stdin_open: true
    tty: true
networks:
  network_2:
    ipam:
      config:
        - subnet: 193.20.3.1/24
