version: '2'
services:
  Bob:
    image: 'alpine-ncat:latest'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.3
  Alice:
    image: 'alpine-ncat:latest'
    stdin_open: true
    tty: true
    networks:
      mySubnet:
        ipv4_address: 193.20.1.2
networks:
  mySubnet:
    ipam:
      config:
        - subnet: 193.20.1.1/24
