version: '2'
services:
  kali:
    image: 'savmil/kali:latest'
    stdin_open: true
    tty: true
    ports:
      - '5000:4200'
    networks:
      sub:
        ipv4_address: 172.18.0.5
    cap_add:
      - ALL
  wireshark:
    image: 'savmil/wireshark:latest'
    stdin_open: true
    tty: true
    ports:
      - '14500:14500'
    networks:
      sub:
        ipv4_address: 172.18.0.4
    environment:
      - XPRA_PW=wireshark
    cap_add:
      - NET_ADMIN
    privileged: true
  client:
    image: 'savmil/ipsecclient:latest'
    stdin_open: true
    tty: true
    networks:
      sub:
        ipv4_address: 172.18.0.3
  server:
    image: 'savmil/ipsec:latest'
    stdin_open: true
    tty: true
    networks:
      sub:
        ipv4_address: 172.18.0.2
networks:
  sub:
    ipam:
      config:
        - subnet: 172.18.0.1/24
